name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    # 每天 UTC 0:00（北京时间早上 8:00）自动检测上游并同步
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持手动点击按钮立即触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'cmliu/CF-Workers-SUB' }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: cmliu/CF-Workers-SUB
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "同步失败，请检查是否存在分支名称冲突。"
          exit 1
